FROM python:3.12.6

# Force the binary layer of the stdout and stderr streams
# to be unbuffered
ENV PYTHONUNBUFFERED=1

# Base directory for the application
# Also used for user directory
ENV APP_ROOT=/home/loader

# Containers should NOT run as root
# (as good practice)
RUN useradd -m -d ${APP_ROOT} -s /bin/sh loader

RUN /usr/local/bin/python -m pip install --upgrade pip && \
    pip install \
        awscli==1.34.28 \
        botocore==1.35.28 \
        boto3==1.35.28 \
        awscli-plugin-endpoint==0.4

# Create an aws config directory
# (in case a config file is mapped into the container)
WORKDIR ${APP_ROOT}/.aws

# Here we synchronise an S3 bucket and path to '/data',
# which is expected to be an external volume.
# Make the data directory (mount point)
WORKDIR /data

# Copy hash prep script...
COPY hash-prep.sh ${APP_ROOT}/
COPY load-neo4j.sh.HEADER ${APP_ROOT}/
COPY load-neo4j.sh.FOOTER ${APP_ROOT}/
# Copy entrypoint and set permissions...
COPY s3-loader-entrypoint.sh ${APP_ROOT}/
RUN chmod 755 ${APP_ROOT}/s3-loader-entrypoint.sh && \
    chmod 755 ${APP_ROOT}/hash-prep.sh && \
    chown -R loader:loader ${APP_ROOT} && \
    chown -R loader:loader /data

# Switch user and move to HOME
USER loader
ENV HOME=${APP_ROOT}
WORKDIR ${APP_ROOT}

CMD ["./s3-loader-entrypoint.sh"]
