version: '3.0'

services:

  graph:
    build:
      context: .
      dockerfile: Dockerfile-fragnet
      args:
        from_tag: ${IMAGE_TAG:-3.5.0}
    image: informaticsmatters/neo4j:3.5.0
    container_name: neo4j
