#!/usr/bin/env bash
#
# A 'prep' script, given a 'prepared' dataset
# that has been extracted to a bucket and path on S3.
# This script concatenates the hash files (on a per-target-file basis)
# and then creates a 'load-neo4j.sh' script that will be used
# to import the data into Neo4j.
#
# NOTE: Only call this if a 'hash5' directory exists in the download directory
#       (passed as the first argument to this script).
#
# As an example all '.csv.gz' files in 'hash5/isomol-nodes/prepared'
# will be concatenated into 'isomol-nodes.csv.gz' in the root of the
# download directory.
#
# Corresponding header files are expected for each hash5 sub-directory
# as these cannot be autogenerated. i.e. in the above example
# a 'header-isomol-nodes.csv' file is expected in the root of the download directory.

: "${APP_ROOT?Need to set APP_ROOT}"

ME=hash-prep.sh

# Move to download directory
# --------------------------
# Check and display the size of the download directory
# before moving to it
download_dir=$1
if [ ! -d "${download_dir}" ]; then
  echo "ERROR: ${download_dir} directory does not exist."
  exit 1
fi
if [ ! -d "${download_dir}/hash5" ]; then
  echo "ERROR: ${download_dir}/hash5 directory does not exist."
  exit 1
fi

echo "($ME) $(date) Size of initial download: $(du -sh ${download_dir})"
pushd ${download_dir}

# Collect all the prepared hashes together
# ----------------------------------------
echo "($ME) $(date) Concatenating 'prepared' files..."
for dir in hash5/*/; do
  if [ -d "${dir}prepared" ]; then
    name=$(echo "${dir}" | cut -f2 -d/)
    target_file="${name}.csv.gz"
    echo "($ME) $(date) + ${target_file}"
    touch ${target_file}
    for hash_file in "${dir}prepared"/*; do
      cat ${hash_file} >> ${target_file}
    done
    # We've dealt with this 'prepared' directory
    # so remove it to reduce our overall disk usage
    rm -rf ${dir}prepared
  fi
done
echo "($ME) $(date) Concatenated"

# Begin load-neo4j.sh
# -------------------
echo "($ME) $(date) Creating load-neo4j.sh..."
cp ${APP_ROOT}/load-neo4j.sh.HEADER load-neo4j.sh

# Add the node files to load-neo4j.sh
# -----------------------------------
# Collect all the nodes.csv.gz files into an ARRAY
# and create --nodes lines
gz_files=(*nodes.csv.gz)
for gz_file in "${gz_files[@]}"; do
  hdr=$(echo ${gz_file} | sed 's/.gz//')
  echo "        --nodes \"header-${hdr},${gz_file}\" \\" >> load-neo4j.sh
done

# Add the relationship files to load-neo4j.sh
# -------------------------------------------
# Collect all the edges.csv.gz files into an ARRAY
# and create --relationships lines
# treating the last file separately
# (to deal with the final 'tee' correctly)
gz_files=(*edges.csv.gz)
for gz_file in "${gz_files[@]::${#gz_files[@]}-1}"; do
  hdr=$(echo ${gz_file} | sed 's/.gz//')
  echo "        --relationships \"header-${hdr},${gz_file}\" \\" >> load-neo4j.sh
done
last_file="${gz_files[@]: -1:1}"
hdr=$(echo ${last_file} | sed 's/.gz//')
echo "        --relationships \"header-${hdr},${last_file}\" 2>&1 | tee /data/data-loader/import.out" >> load-neo4j.sh

# End load-neo4j.sh
# -----------------
cat ${APP_ROOT}/load-neo4j.sh.FOOTER >> load-neo4j.sh

# Now remove the source hash files (to save space)
# ------------------------------------------------
# And return to the launch directory
echo "($ME) $(date) Removing hash5 directory..."
rm -rf ${download_dir}/hash5
popd

echo "($ME) $(date) Size of final download: $(du -sh ${download_dir})"

echo "($ME) $(date) Done"
