---

# The Project and PVC are expected to exist...

- name: Login (user)
  command: oc login https://{{ okd_master_hostname }} -u {{ okd_user }} -p {{ okd_user_password }}
  changed_when: False

- name: Get Projects
  command: oc get projects
  register: projects_result
  changed_when: False

- name: Assert project existance ({{ graph_project }})
  assert:
    that: projects_result.stdout|regex_search('^%s' % graph_project, multiline=True)

- name: Get PVCs
  command: oc get pvc --namespace={{ graph_project }}
  register: pvc_result
  changed_when: False

- name: Assert PVC existance
  assert:
    that: pvc_result.stdout|regex_search('^%s' % graph_pvc, multiline=True)

# Deploy secrets

- name: Deploy secrets
  k8s:
    definition: "{{ lookup('template', item)|from_yaml }}"
  loop:
  - secrets.yaml.j2

# Deploy the loader...

- name: Remove pre-existing loader (Job)
  k8s:
    definition: "{{ lookup('template', item)|from_yaml }}"
    state: absent
  loop:
  - loader-job.yaml.j2

- name: Deploy Loader (Job)
  k8s:
    definition: "{{ lookup('template', item)|from_yaml }}"
  loop:
  - loader-job.yaml.j2

- name: Wait for Loader (Job)
  shell: >-
    oc describe jobs/graph-loader --namespace={{ graph_project }}
    | grep '1 Succeeded'
  delay: 20
  retries: "{{ (graph_loader_pod_ready_timeout|int / 20)|int }}"
  register: result
  until: result.rc == 0

# Deploy the graph...

- name: Deploy Graph
  k8s:
    definition: "{{ lookup('template', item)|from_yaml }}"
  loop:
  - graph-deployment.yaml.j2
  - graph-http-service.yaml.j2
  - graph-bolt-service.yaml.j2

- name: Wait for Graph
  shell: >-
    oc get po --namespace={{ graph_project }}
    | grep {{ item }} | grep -v deploy | grep 1/1 > /dev/null
  delay: 60
  retries: "{{ (graph_pod_ready_timeout|int / 60)|int }}"
  register: result
  until: result.rc == 0
  loop:
  - graph-pod
  changed_when: false

- name: Deploy application route
  k8s:
    definition: "{{ lookup('template', item)|from_yaml }}"
  loop:
  - graph-route.yaml.j2
  when: graph_enable_route|bool
